---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age18emt2h8sq2qwvepuska69ew9qkstw0raduye2su58thedh2jmynslct2e7"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age18emt2h8sq2qwvepuska69ew9qkstw0raduye2su58thedh2jmynslct2e7"
