apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:lehIEnomDTwToOrIgBKoOGkNw8hBaislIeDLrsiN/ss=,iv:gvS1TRzDE1YXMSuZ+P4kz/+31372/KLEkj4m91UEPIc=,tag:RikrXdFQSrr/gWeDJEkr0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18emt2h8sq2qwvepuska69ew9qkstw0raduye2su58thedh2jmynslct2e7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMmphY3FKOHN5S3lXejZ1
            VHhTL3ZFSWJEVEk4RFUySlBPWXpYbitCcEI4CndFMzc1eDZWVHNiZjlNQWRvVnhh
            QUIxUEV4WFhhb24vSzArUXd1bFY5SFkKLS0tIEE5bllPS3huT1JteWxMQ1JuK0Zj
            Ulo0WHdCUzRpZGtBSU0xM3BiZHFwU1EKL0UOhVuKKwAAOCEoVf9/8w0IZ9FV+jDH
            iPs9qKxPvcGKpjmuMGXncs9n64z2IFqmrVhd/DeOJcvxve/cNfTlgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T13:18:01Z"
    mac: ENC[AES256_GCM,data:wZLYx4rW9AbMS+RJV3ejXmsRQmNbt3GZcSqSLr4u//PH5ZnkG0oHkfsU3PYIJ4B9fAmw7iiWyQe/dD4TDQ+nB7dfFD8jum9JB9eNMPL+8DclubHTmKcITgFnNHwrmOHR8ml1uDh7CsQ7gGexjJiw3BlSMl7HKFhzSXBNILD7ouU=,iv:GDKFIGKdNBBu4C2aQUD1FnJ89ymlGDuEwkiULJy0gTQ=,tag:+eOMqARHZhfMcSTe2QZC5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
